### ISSUE TITLE
init website

### ISSUE THREAD

**Issue by despiegk** [ourworld-tsc/www_ourverse#1]
- make zola website, start from what was done for ThreeFold 
- empty content
- move content (can be copy paste for now from website online) into this website
- publish
- use github pages to show the result
- readme links to github pages
- instructions how to build * develop (see threefold.io)

**Comment by despiegk** [comment]
basic stuff done but pictures still broken
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/6021844/180598405-f664bb47-6885-4412-aacf-5838f325170b.png">

the basic flow works, building to github pages

**Comment by sasha-astiadi** [comment]
live https://ourverse.tf/
