### ISSUE TITLE
website looks broken 

### ISSUE THREAD

**Issue by sasha-astiadi** [ourworld-tsc/www_ourverse#4]
https://github.com/ourworld-tsc/www_ourverse

https://ourverse.tf/
<img width="1440" alt="Screenshot 2022-10-25 at 14 18 40" src="https://user-images.githubusercontent.com/43240801/197771424-7b11844c-7ce4-475b-b004-beaa1014b6aa.png">

pages look broken, or is it just my laptop?
please take a look, i couldnt fix it @timurgordon @ehab-hassan

**Comment by ehab-hassan** [comment]
Ok that is run from old repo @PeterNashaat fixed it 
production : https://www.ourverse.tf/
staging : https://www2.ourverse.tf/
please keep in mind the website not final still need content some pages to add.
